apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
data:
  default.conf: |
    server {
      listen 80;
      server_name _;
      location / {
        root   /usr/share/nginx/html;
        index  index.html;
        try_files $uri $uri/ =404;
      }
    }